# Generated by Django 6.0.3 on 2026-05-01 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlisting_image_auctionlisting_is_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='email',
            field=models.EmailField(blank=True, help_text='Email address for auction-end notifications', max_length=254),
        ),
    ]
