# Generated by Django 6.0.3 on 2026-06-05 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription_required',
            field=models.BooleanField(default=True, help_text='Uncheck to allow this user to bid without a PayPal subscription (admin override).'),
        ),
    ]
