# Generated by Django 6.0.3 on 2026-06-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='buy_now_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='listing_type',
            field=models.CharField(choices=[('auction', 'Auction'), ('buy_now', 'Buy It Now')], default='auction', max_length=8),
        ),
    ]
