# Generated by Django 6.0.3 on 2026-06-05 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_listingcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='notify_on_comments',
            field=models.BooleanField(default=True, help_text='Email this seller when a buyer posts a question on their listing.'),
        ),
    ]
