# Generated by Django 6.0.3 on 2026-07-29 04:20

from django.db import migrations, models


def approve_existing_accounts(apps, schema_editor):
    """
    Grandfather in everyone who already had an account.

    ``is_approved`` defaults to False so that *new* sign-ups wait for an admin.
    Applied as-is to an existing database that default would also lock out every
    current member — including paying subscribers — the next time they log in,
    with no way for them to tell why. Approve every profile that exists at
    migration time; the gate then only affects accounts created afterwards.
    """
    UserProfile = apps.get_model("auctions", "UserProfile")
    UserProfile.objects.update(is_approved=True)


def unapprove_all(apps, schema_editor):
    """No-op reverse: the column is dropped by the reversed AddField anyway."""


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0012_seller_notify_on_comments"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_approved",
            field=models.BooleanField(
                default=False,
                help_text="Admin must approve new accounts before they can log in.",
            ),
        ),
        # Same migration as the AddField on purpose: there must be no state in
        # which the column exists but the backfill has not run.
        migrations.RunPython(approve_existing_accounts, unapprove_all),
    ]
