# Generated by Django 6.0.3 on 2026-08-02 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0014_verify_pre_existing_emails"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="email_login_code_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Require an emailed one-time code at login (in addition to password). Staff cannot disable this. Ignored if the user has an authenticator app (TOTP) configured — TOTP replaces the email code step.",
            ),
        ),
    ]
