# Generated by Django 6.0.3 on 2026-08-04 04:05

from django.db import migrations, models


def stock_existing_buy_now_listings(apps, schema_editor):
    """
    Give every pre-existing Buy It Now listing a stock count of one.

    The new columns are nullable, and a buy_now listing with a null
    quantity_remaining reads as sold out — so without this backfill every live,
    unsold Buy It Now listing becomes unpurchasable the moment this migration
    lands, with nothing on the page explaining why.

    One unit is the honest translation: before stock existed, a buy_now listing
    sold exactly once, recorded by setting `winner`. So listings that already
    have a winner are marked sold (0 remaining) and the rest keep their single
    unit available. A listing closed at its end time without selling keeps
    remaining=1, which is accurate — is_closed is what stops it being bought.

    Auction listings are left null: they sell one lot to one winner and do not
    use these fields.
    """
    AuctionListing = apps.get_model("auctions", "AuctionListing")
    buy_now = AuctionListing.objects.filter(listing_type="buy_now")
    buy_now.filter(winner__isnull=False).update(
        quantity_available=1, quantity_remaining=0
    )
    buy_now.filter(winner__isnull=True).update(
        quantity_available=1, quantity_remaining=1
    )


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0015_userprofile_email_login_code_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="quantity_available",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Total units available for this Buy It Now listing.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="quantity_remaining",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Units still available for purchase. Set equal to quantity_available when the listing is created; decremented as purchases come in.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="auctionlisting",
            name="shipping_mode",
            field=models.CharField(
                choices=[
                    ("flat", "Flat fee per order"),
                    ("per_item", "Multiplied by quantity"),
                ],
                default="flat",
                help_text="How shipping is calculated when a buyer takes more than one. Flat fee: the buyer pays shipping once no matter how many they buy. Per item: shipping is multiplied by the quantity they buy.",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="invoice",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1,
                help_text="Units this buyer purchased. Always 1 for auction wins; can be more for a multi-quantity Buy It Now listing, where one listing produces one invoice per buyer.",
            ),
        ),
        # Same migration as the AddFields on purpose: there must be no state in
        # which the columns exist but existing buy_now listings read sold out.
        # Irreversible — the reversed AddField drops the columns anyway.
        migrations.RunPython(
            stock_existing_buy_now_listings, migrations.RunPython.noop
        ),
    ]
