# Generated by Django 6.0.3 on 2026-08-15 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0016_auctionlisting_quantity_available_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="shipping_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Shipping cost for this listing. Leave blank to use the seller's standard shipping fee. Combined with the shipping mode above: a flat fee is charged once per order, a per-item fee is multiplied by the quantity bought.",
                max_digits=7,
                null=True,
            ),
        ),
    ]
