# Generated by Django 6.0.3 on 2026-09-07 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0018_merge_seller_into_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="apple_pay_info",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Apple Pay"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="cashapp_info",
            field=models.CharField(blank=True, max_length=255, verbose_name="Cash App"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="google_pay_info",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Google Pay"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="paypal_info",
            field=models.CharField(blank=True, max_length=255, verbose_name="PayPal"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="venmo_info",
            field=models.CharField(blank=True, max_length=255, verbose_name="Venmo"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="zelle_info",
            field=models.CharField(blank=True, max_length=255, verbose_name="Zelle"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="seller_payment_methods",
            field=models.TextField(
                blank=True,
                help_text='Anything the named fields above do not cover — a mailing address for cheques, "cash at pickup", or a note about how they prefer to be paid.',
                verbose_name="Other payment notes",
            ),
        ),
    ]
