# Generated by Django 6.0.3 on 2026-09-07 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0020_faq_and_site_pages"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CombinedInvoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("sent", "Sent")],
                        default="draft",
                        max_length=5,
                    ),
                ),
                (
                    "shipping_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="If set, replaces the sum of the line items' shipping fees. Use it when several plants ship in one box for less than the individual fees add up to.",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Flat dollar discount applied to this invoice total.",
                        max_digits=8,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Shown to the buyer on the invoice email."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combined_invoices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"profile__is_seller": True},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="combined_invoices_as_seller",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="invoice",
            name="combined_invoice",
            field=models.ForeignKey(
                blank=True,
                help_text="The combined invoice this line belongs to. Empty means it has not been billed to the buyer yet.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="line_items",
                to="auctions.combinedinvoice",
            ),
        ),
        migrations.AddConstraint(
            model_name="combinedinvoice",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "draft")),
                fields=("buyer", "seller"),
                name="one_open_draft_per_buyer_and_seller",
            ),
        ),
    ]
