# Generated by Django 6.0.3 on 2026-09-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0021_combined_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="auctionlisting",
            name="additional_item_discount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0,
                help_text="Amount off each unit beyond the first, for Buy It Now listings. Set per listing by the admin — buy 3 of a $12 plant with a $3 discount and it costs $12 + $9 + $9. Leave at 0 for no discount.",
                max_digits=6,
            ),
        ),
    ]
