# Generated by Django 6.0.3 on 2026-09-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0022_listing_quantity_discount"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "header_banner_image",
                    models.ImageField(
                        blank=True,
                        help_text="The main image at the top of every page. Wide works best — it sits beside the site name. Leave empty to use the built-in logo.",
                        upload_to="site/",
                    ),
                ),
                (
                    "app_icon_image",
                    models.ImageField(
                        blank=True,
                        help_text="Square image used as the browser tab icon and the home-screen icon on phones. Upload a square image — anything else will be squashed by the browser. Leave empty to use the built-in favicon.",
                        upload_to="site/",
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site settings",
                "verbose_name_plural": "Site settings",
            },
        ),
    ]
