"""
Django settings for auction_site project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR.parent / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-development-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# Parse ALLOWED_HOSTS from environment (comma-separated)
# In production set ALLOWED_HOSTS=yourdomain.com in the environment.
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'unfold.contrib.forms',
    'unfold.contrib.inlines',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    
    # Third-party apps
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    'allauth.socialaccount.providers.facebook',
    'allauth.socialaccount.providers.microsoft',
    'allauth.mfa',
    'django_apscheduler',

    # Local apps
    'auctions.apps.AuctionsConfig',
]

SITE_ID = 1

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'auction_site.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'auction_site' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'auction_site.context_processors.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'auction_site.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

_db_engine = os.getenv('DATABASE_ENGINE', 'django.db.backends.sqlite3')

if _db_engine == 'django.db.backends.sqlite3':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': _db_engine,
            'NAME': os.getenv('DATABASE_NAME', ''),
            'USER': os.getenv('DATABASE_USER', ''),
            'PASSWORD': os.getenv('DATABASE_PASSWORD', ''),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Chicago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'auction_site' / 'static',
]

MEDIA_ROOT = BASE_DIR / 'media'

# ============================================================================
# Cloudflare R2 Media Storage
# ============================================================================

_r2_account_id = os.getenv('CF_R2_ACCOUNT_ID', '')
_r2_access_key = os.getenv('CF_R2_ACCESS_KEY_ID', '')
_r2_secret_key = os.getenv('CF_R2_SECRET_ACCESS_KEY', '')
_r2_bucket = os.getenv('CF_R2_BUCKET_NAME', '')
_r2_custom_domain = os.getenv('CF_R2_CUSTOM_DOMAIN', '')

if _r2_account_id and _r2_access_key and _r2_secret_key and _r2_bucket:
    DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': 'django.contrib.staticfiles.storage.StaticFilesStorage',
        },
    }
    AWS_ACCESS_KEY_ID = _r2_access_key
    AWS_SECRET_ACCESS_KEY = _r2_secret_key
    AWS_STORAGE_BUCKET_NAME = _r2_bucket
    AWS_S3_ENDPOINT_URL = f'https://{_r2_account_id}.r2.cloudflarestorage.com'
    AWS_S3_REGION_NAME = 'auto'
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False
    if _r2_custom_domain:
        AWS_S3_CUSTOM_DOMAIN = _r2_custom_domain
        MEDIA_URL = f'https://{_r2_custom_domain}/'
    else:
        MEDIA_URL = f'https://{_r2_account_id}.r2.cloudflarestorage.com/{_r2_bucket}/'
else:
    MEDIA_URL = '/media/'

# Default primary key field type
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ============================================================================
# Security hardening
# ============================================================================

# Prevent browsers from MIME-sniffing a response away from the declared content-type.
SECURE_CONTENT_TYPE_NOSNIFF = True

# Deny all framing to prevent clickjacking.
X_FRAME_OPTIONS = 'DENY'

# Secure cookies — only sent over HTTPS.  Set to False when running on plain HTTP (no Cloudflare yet).
SESSION_COOKIE_SECURE = os.getenv('SESSION_COOKIE_SECURE', str(not DEBUG)) == 'True'
CSRF_COOKIE_SECURE = os.getenv('CSRF_COOKIE_SECURE', str(not DEBUG)) == 'True'

# Trusted origins for CSRF — required when behind a reverse proxy or on a non-standard port.
_csrf_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if _csrf_origins:
    CSRF_TRUSTED_ORIGINS = [o.strip() for o in _csrf_origins.split(',')]

# HSTS — off by default; set SECURE_HSTS_SECONDS=31536000 in production once HTTPS is confirmed.
SECURE_HSTS_SECONDS = int(os.getenv('SECURE_HSTS_SECONDS', '0'))
SECURE_HSTS_INCLUDE_SUBDOMAINS = os.getenv('SECURE_HSTS_INCLUDE_SUBDOMAINS', 'False') == 'True'
SECURE_HSTS_PRELOAD = os.getenv('SECURE_HSTS_PRELOAD', 'False') == 'True'

# Redirect all HTTP to HTTPS in production — set SECURE_SSL_REDIRECT=True in env.
SECURE_SSL_REDIRECT = os.getenv('SECURE_SSL_REDIRECT', 'False') == 'True'

# Tell Django it's behind an HTTPS reverse proxy (nginx) in production.
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Silence deployment checks that are intentionally controlled via environment variables.
# W004 (HSTS) and W008 (SSL redirect) are opt-in; see SECURITY.md for production setup.
SILENCED_SYSTEM_CHECKS = ['security.W004', 'security.W008']

# ============================================================================
# Unfold Admin Configuration
# ============================================================================

UNFOLD = {
    "SITE_TITLE": "ASQ Daylily Auctions",
    "SITE_HEADER": "ASQ Daylily Auctions Admin",
    "SITE_SYMBOL": "storefront",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "COLORS": {
        "primary": {
            "50": "240 249 255",
            "100": "224 242 254",
            "200": "186 230 253",
            "300": "125 211 252",
            "400": "56 189 248",
            "500": "79 163 209",
            "600": "44 90 123",
            "700": "26 58 82",
            "800": "12 74 110",
            "900": "8 47 73",
            "950": "8 47 73",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation_header": [
            {
                "title": "← Back to Main Site",
                "link": "/",
            },
        ],
        "navigation": [
            {
                "title": "Auctions",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "Listings",
                        "icon": "gavel",
                        "link": reverse_lazy("admin:auctions_auctionlisting_changelist"),
                    },
                    {
                        "title": "Categories",
                        "icon": "category",
                        "link": reverse_lazy("admin:auctions_auctioncategory_changelist"),
                    },
                    {
                        "title": "Sellers",
                        "icon": "storefront",
                        "link": reverse_lazy("admin:auctions_seller_changelist"),
                    },
                    {
                        "title": "Bids",
                        "icon": "price_check",
                        "link": reverse_lazy("admin:auctions_bid_changelist"),
                    },
                ],
            },
            {
                "title": "Invoices & Reporting",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Invoices",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:auctions_invoice_changelist"),
                    },
                    {
                        "title": "Reports Dashboard",
                        "icon": "bar_chart",
                        "link": reverse_lazy("reports_dashboard"),
                    },
                    {
                        "title": "Export CSV",
                        "icon": "download",
                        "link": reverse_lazy("reports_export_csv"),
                    },
                ],
            },
            {
                "title": "Weekly Setup",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "New Weekly Auction",
                        "icon": "event",
                        "link": reverse_lazy("weekly_setup"),
                    },
                ],
            },
            {
                "title": "Users",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "Users",
                        "icon": "person",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Wishlists",
                        "icon": "favorite",
                        "link": reverse_lazy("admin:auctions_wishlist_changelist"),
                    },
                ],
            },
        ],
    },
}

# ============================================================================
# Django AllAuth Configuration
# ============================================================================

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

# Account settings — email-only login, no username required at signup
ACCOUNT_LOGIN_METHODS = {'email'}
ACCOUNT_SIGNUP_FIELDS = ['email*', 'password1*', 'password2*']
ACCOUNT_SIGNUP_FORM_CLASS = 'auctions.forms.CustomSignupForm'
ACCOUNT_SESSION_REMEMBER = True
ACCOUNT_EMAIL_VERIFICATION = 'optional'

# MFA Configuration
MFA_SUPPORTED_AUTH_FORMS = [
    'allauth.mfa.totp.forms.ActivateTOTPForm',
]

# Social account settings
SOCIALACCOUNT_AUTO_SIGNUP = True
SOCIALACCOUNT_EMAIL_REQUIRED = True
SOCIALACCOUNT_EMAIL_VERIFICATION = 'none'  # provider has already verified the email

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': os.getenv('GOOGLE_CLIENT_ID', ''),
            'secret': os.getenv('GOOGLE_CLIENT_SECRET', ''),
        },
        'SCOPE': ['profile', 'email'],
        'AUTH_PARAMS': {'access_type': 'online'},
    },
    'facebook': {
        'APP': {
            'client_id': os.getenv('FACEBOOK_APP_ID', ''),
            'secret': os.getenv('FACEBOOK_APP_SECRET', ''),
        },
        'METHOD': 'oauth2',
        'SCOPE': ['email', 'public_profile'],
    },
    'microsoft': {
        'APP': {
            'client_id': os.getenv('MICROSOFT_CLIENT_ID', ''),
            'secret': os.getenv('MICROSOFT_CLIENT_SECRET', ''),
        },
        'TENANT': 'common',
    },
}

# Email backend (for development - using console backend)
# Override in .env with: EMAIL_BACKEND=django.core.mail.backends.smtp.EmailBackend
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend')

# Email configuration (optional - only if using SMTP)
if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
    EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
    DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# Admin / notification email
ADMIN_EMAIL = os.getenv('ADMIN_EMAIL', '')

# Redirect URLs
LOGIN_REDIRECT_URL = '/'
ACCOUNT_LOGOUT_REDIRECT_URL = '/'
ACCOUNT_ADAPTER = 'auctions.adapters.AccountAdapter'
